whitelist-status: false # Is the whitelist enabled

bypass-permission: "VelocityWhitelist.bypass" # A permission which would still permit the player to join even if he's not whitelisted
permission: "VelocityWhitelist.use" # General permission for all commands
join-notifies-permission: "VelocityWhitelist.joinnotify" # Anyone with this permission will recieve a message when a player tries to join

motd-enabled: true # Do you want this plugin to modify the motd
disable-playercount: true # Should the plugin disable the showed player count
motd-message: "the server is currently under maintenance"
ping-message: "in maintenance"

kick-message: "the server is currently under maintenance"
add-message: "Added {player} to the whitelist!"
whitelist-enabled: "whitelist in now enabled"
whitelist-disabled: "whitelist in now disabled"
whitelist-already-on: "the whitelist is already on"
whitelist-already-off: "the whitelist is already off"
remove-message: "Removed {player} from the whitelist!"
list-message: "Whitelist players:"
empty-list-message: "The whitelist is empty!"
usage-message: "/vwhitelist <subcommand>"
alreadywhitelisted-message: "{player} is already whitelisted!"
player-not-whitelisted-message: "{player} is not in the whitelist!"
player-doesntexist: "{player} doesn't exist!"
reload-message: "the config has been reloaded!"
join-notify-message: "{player} tried to join the server!"