whitelist-status: true # Is the whitelist enabled

bypass-permission: "" # A permission which would still permit the player to join even if he's not whitelisted
permission: "VelocityWhitelist.use" # General permission for all commands

kick-message: "the server is currently under maintenance"
add-message: "Added {player} to the whitelist!"
whitelist-enabled: "whitelist in now enabled"
whitelist-disabled: "whitelist in now disabled"
whitelist-already-on: "the whitelist is already on"
whitelist-already-off: "the whitelist is already off"
remove-message: "Removed {player} from the whitelist!"
list-message: "Whitelist players:"
empty-list-message: "The whitelist is empty!"
usage-message: "/vwhitelist <subcommand>"
alreadywhitelisted-message: "{player} is already whitelisted!"
player-not-whitelisted-message: "{player} is not in the whitelist!"
player-doesntexist: "{player} doesn't exist!"